name: focus_vibe_pomodoro
description: Advanced Pomodoro timer with calendar tracking and a focus vibe aesthetic.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_heatmap_calendar: ^1.0.5
  collection: ^1.18.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true