name: Flutter Setup for FlutLab

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # Używa domyślnej stabilnej wersji, możesz dostosować
    - run: flutter doctor -v # Sprawdza wersję Fluttera
    - run: flutter create --platforms android .
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git add .
    - run: git commit -m "Add Android folder with Flutter setup"
    - run: git push
