name: Flutter Setup for FlutLab

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter doctor -v
    - run: |
        if [ ! -d "ios" ]; then
          flutter create --platforms ios .
        fi
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git add .
    - run: git commit -m "Add iOS folder with Flutter setup" || echo "No changes to commit"
    - run: git push
